### ISSUE TITLE
Bug: [function.preg-match-all]: Compilation failed: POSIX collating elements are not supported at offset 30

### ISSUE THREAD

**Issue by ginatrapani** [ThinkUpLLC/ThinkUp#1287]
The Post object's URL extraction regex is failing for some users. The exact error text is:

Warning: preg_match_all() [function.preg-match-all]: Compilation failed: POSIX collating elements are not supported at offset 30 in /home/whostole/public_html/thinkup/_lib/model/class.Post.php on line 265

As reported in this mailing list thread:

https://groups.google.com/d/topic/thinkupapp/_4PvQrWvUs4/discussion

I can't reproduce this on PHP 5.3 or PHP 5.2.6. But thes StackOverflow discussions suggests this may be specific to the PHP version the user is running, which is PHP 5.2.17:

http://stackoverflow.com/questions/7173787/compilation-failed-posix-collating-elements-are-not-supported

http://stackoverflow.com/questions/9255570/php-warning-about-posix-collating-element

So first, we need to reproduce the error on PHP 5.2.17 - dependent on issue #1285. Then if it is indeed a regex problem specific to that version, need to rejigger the regex to work on all versions of PHP 5.2 and greater.
